apiVersion: apps/v1
kind: Deployment
metadata:
  name: LectureSystem
  labels:
    app: LectureSystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LectureSystem
  template:
    metadata:
      labels:
        app: LectureSystem
    spec:
      containers:
        - name: LectureSystem
          image: username/LectureSystem:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5